=== jfix/authoring/models/schemas/products/toc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="urn:oecd:names:xmlns:authoring:product" targetNamespace="urn:oecd:names:xmlns:authoring:product" xmlns:xd="http://www.oecd.org/ns/schema/xdocs">

  <xs:annotation>
    <xs:documentation><section xmlns="http://docbook.org/ns/docbook">
        <title>OECD Schemas</title>
        <subtitle>Table of Contents Model</subtitle>
        <revhistory>
          <title>Change Log</title>
          <revision>
            <revnumber>1</revnumber>
            <date>2012-11-20</date>
            <author>JC</author>
            <revremark>Initial Version</revremark>
          </revision>
        </revhistory>
      </section>
    </xs:documentation>
  </xs:annotation>
  
  <!-- IMPORTS AND INCLUDES -->
  <xs:include schemaLocation="../components/attributes.xsd"/>
  <xs:include schemaLocation="../components/titles.xsd"/>

  <!-- GLOBAL ELEMENTS -->
  <xs:element name="toc" type="oecdToCType" id="toc"/>
  
  <xs:complexType name="oecdToCType" id="oecdToCType">
    <xs:annotation>
      <xs:documentation>
        <section xmlns="http://docbook.org/ns/docbook">
          
        </section>
      </xs:documentation>
    </xs:annotation>
    
    <xs:group ref="oecdToCTypeContent"/>
    <xs:attributeGroup ref="oecdLinkingAttributes"/>
    <xs:attributeGroup ref="oecdCommonAttributes"/>
  </xs:complexType>
  
  <xs:group name="oecdToCTypeContent" id="oecdToCTypeContent">
    <xs:annotation>
      <xs:documentation>
        <section xmlns="http://docbook.org/ns/docbook">
          <para>Content for ToCs as a group for easy overrides and reuse.</para>
          <revhistory>
            <title>Change Log</title>
            <revision>
              <revnumber/>
              <date/>
              <author/>
              <revremark/>
            </revision>
          </revhistory>
        </section>
      </xs:documentation>
    </xs:annotation>
    
    <xs:sequence>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:group ref="oecdTitleGroup" minOccurs="0"/>
        </xs:choice>
      </xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="toc-sect" type="oecdTocSectionType" maxOccurs="unbounded"/>
        <xs:element name="toc-entry" type="oecdTocEntryType" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:sequence>
  </xs:group>
  
  
  <xs:complexType name="oecdTocSectionType"  id="oecdTocSectionType">
    <xs:group ref="oecdTocSectionTypeContent"/>
    <xs:attributeGroup ref="oecdCommonAttributes"/>
    <xs:attributeGroup ref="oecdLinkingAttributes"/>
    <xs:attribute name="pagenum"/>
  </xs:complexType>
  
  
  <xs:group name="oecdTocSectionTypeContent" id="oecdTocSectionTypeContent">
    <xs:annotation>
      <xs:documentation>
        <section xmlns="http://docbook.org/ns/docbook">
          <para>Section content for ToCs as a group for easy overrides and reuse.</para>
          <revhistory>
            <title>Change Log</title>
            <revision>
              <revnumber/>
              <date/>
              <author/>
              <revremark/>
            </revision>
          </revhistory>
        </section>
      </xs:documentation>
    </xs:annotation>
    
    <xs:sequence>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:group ref="oecdTitleGroup" minOccurs="0"/>
        </xs:choice>
      </xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="toc-sect" type="oecdTocSectionType" maxOccurs="unbounded"/>
        <xs:element name="toc-entry" type="oecdTocEntryType" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:sequence>
  </xs:group>
  
  <xs:complexType name="oecdTocEntryType"  id="oecdTocEntryType" mixed="true">
    <xs:annotation>
      <xs:documentation>
        <section xmlns="http://docbook.org/ns/docbook">
          <para>An entry in a toc.</para>
        </section>
      </xs:documentation>
    </xs:annotation>
    <xs:group ref="oecdTocEntryTypeContent"/>
    <xs:attributeGroup ref="oecdCommonAttributes"/>
    <xs:attributeGroup ref="oecdLinkingAttributes"/>
    <xs:attribute name="pagenum"/>
  </xs:complexType>
  
  
  <xs:group name="oecdTocEntryTypeContent" id="oecdTocEntryTypeContent">
    <xs:annotation>
      <xs:documentation>
        <section xmlns="http://docbook.org/ns/docbook">
          <para>Entry content for ToCs as a group for easy overrides and reuse.</para>
          <revhistory>
            <title>Change Log</title>
            <revision>
              <revnumber/>
              <date/>
              <author/>
              <revremark/>
            </revision>
          </revhistory>
        </section>
      </xs:documentation>
    </xs:annotation>
    
    <xs:sequence>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:group ref="oecdTitleGroup" minOccurs="0"/>
        </xs:choice>
      </xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="toc-sect" type="oecdTocSectionType" maxOccurs="unbounded"/>
        <xs:element name="toc-entry" type="oecdTocEntryType" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:sequence>
  </xs:group>

</xs:schema>

=== jfix/authoring/models/tests/authoring/UnitTest/Products/ToCs/Input/odp/toc.xml
<?xml version="1.0" encoding="UTF-8"?>
<toc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oecd:names:xmlns:authoring:product ../../../../../../../schemas/products/toc.xsd" xmlns="urn:oecd:names:xmlns:authoring:product" xmlns:xlink="http://www.w3.org/1999/xlink" xml:id="toc-0001">

    <title xml:id="title-0001">Table of Contents</title>


    <toc-sect xml:id="toc-sect-0001">
        <toc-entry xlink:href="abs-0001" pagenum="2">Abstract</toc-entry>
    </toc-sect>

    <toc-sect xml:id="toc-sect-0002">
        <toc-entry xlink:href="art-0001" pagenum="5">HOW IMPORTANT IS WEALTH FOR EXPLAINING HOUSEHOLD CONSUMPTION OVER THE RECENT CRISIS? AN EMPIRICAL STUDY FOR THE UNITED STATES, JAPAN AND THE EURO AREA</toc-entry>

        <toc-sect xml:id="toc-sect-0002-sub-0001">
            <toc-entry pagenum="5">Introduction and summary of the study</toc-entry>

            <toc-sect xml:id="toc-sect-0002-sub-0001-sub-0001">

                <title>Section 1.1</title>
                <toc-entry pagenum="5" label="1.1">Scope and objectives of the study</toc-entry>
                <toc-entry pagenum="6" label="1.2">Principal findings and contributions</toc-entry>
                <toc-entry pagenum="7" label="1.3">Some elements of consumption behaviour theory</toc-entry>
                <toc-entry pagenum="9" label="1.4">Some elements of recent literature review on wealth effects on consumption</toc-entry>
            </toc-sect>


            <toc-sect>
                <toc-entry>
                    <!--
            2.	Wealth effects in US consumer behaviour: the importance of housing and financial wealth	12
            2.1	Some details about the dataset	12
            2.2	The long-run determinants of US consumption	12
            2.3	Short-run behaviour of US consumption	18
            3.	Wealth effects in Japan: small effects from housing, but large financial wealth effects	21
            3.1	Some properties of the data	21
            3.2	Estimation of long-run consumption in Japan	22
            3.3	Some interpretation of the long-run results	23
            3.4	Short-term dynamics of Japanese consumption	25
            4.	Consumption in the euro area: smaller but significant wealth effects	27
            4.1	The dataset	27
            4.2	Estimation of the long-run consumption in the euro area	28
            4.3	Some interpretation of the long-run results	29
            4.4	Short-term dynamics of euro area consumption	31
            5.	Cross country comparison of overall wealth effects: short-term and long-term response functions	33
            6.	How important are changes in wealth in forecasting consumption over the recent crisis?	35
            7.	How sensitive are long-run household savings to asset prices?	37
            8.	Conclusion and further work	40
                
                -->
                </toc-entry>
            </toc-sect>
        </toc-sect>
    </toc-sect>

    <toc-sect xml:id="toc-sect-0003">
        <toc-entry xlink:href="bib-0001" pagenum="41">BIBLIOGRAPHY</toc-entry>
    </toc-sect>

    <toc-sect xml:id="toc-sect-0004">
        <toc-entry xlink:href="ann-0001" pagenum="44">ANNEX</toc-entry>
        <toc-sect xml:id="toc-sect-0004-sub-0001">
            <toc-entry xlink:href="ann-0001-sub-001" pagenum="44" label="A.1">Notations</toc-entry>
            <toc-entry xlink:href="ann-0001-sub-001" pagenum="44" label="A.2">Some additional evidence on cointegration between consumption, wealth and income</toc-entry>
        </toc-sect>
    </toc-sect>

    <toc-sect xml:id="toc-sect-0005">
        <title>Boxes</title>
        <toc-entry pagenum="8" label="Box 1." xlink:href="box-0001">Estimated coefficients, elasticities and marginal propensities to consume</toc-entry>
    </toc-sect>

    <toc-sect xml:id="toc-sect-0006">
        <title>Tables</title>
        <toc-entry label="1." pagenum="11" xlink:href="table-001">Summary of some results from the literature</toc-entry>
        <toc-entry label="2." pagenum="13" xlink:href="table-002">Order of integration in the US data, in level and in first difference</toc-entry>
        <toc-entry label="3." pagenum="15" xlink:href="table-003">Selected long-term US regressions</toc-entry>
        <toc-entry label="4." pagenum="19" xlink:href="table-004">Selected short-term regressions for the United States</toc-entry>
        <toc-entry label="5." pagenum="22" xlink:href="table-005">Order of integration in the Japanese data, in level and in differences</toc-entry>
        <toc-entry label="6." pagenum="23" xlink:href="table-006">Selected long-term regressions for Japan</toc-entry>
        <toc-entry label="7." pagenum="26" xlink:href="table-007">Selected short-term regressions for Japan</toc-entry>
        <toc-entry label="8." pagenum="28" xlink:href="table-008">Order of integration in the euro area data, in level and in first difference</toc-entry>
        <toc-entry label="9." pagenum="29" xlink:href="table-009">Selected long-term regressions for the euro area</toc-entry>
        <toc-entry label="10." pagenum="32" xlink:href="table-010">Selected short-term regressions for the euro area</toc-entry>
        <toc-entry label="11." pagenum="36" xlink:href="table-011">Compared forecasting errors of US consumption</toc-entry>
        <toc-entry label="12." pagenum="36" xlink:href="table-012">Compared forecasting errors of consumption in Japan</toc-entry>
        <toc-entry label="13." pagenum="37" xlink:href="table-013">Compared forecasting errors of euro area consumption</toc-entry>
        <toc-entry label="A1." pagenum="44" xlink:href="table-014">Definition of variables</toc-entry>
        <toc-entry label="A2." pagenum="46" xlink:href="table-015">Other methods to estimate the US long-run consumption</toc-entry>
        <toc-entry label="A3." pagenum="47" xlink:href="table-016">Other methods to estimate the Japanese long-run relation</toc-entry>
        <toc-entry label="A4." pagenum="49" xlink:href="table-017">Other methods to estimate the euro area long-run relation</toc-entry>


    </toc-sect>

    <toc-sect xml:id="toc-sect-0007">
        <title>Figures</title>
        <toc-entry label="1." pagenum="17" xlink:href="fig-001">Residuals of the long-term benchmark regression for the United States</toc-entry>
        <toc-entry label="2." pagenum="17" xlink:href="fig-002">Stocks of US household wealth</toc-entry>
        <toc-entry label="3." pagenum="18" xlink:href="fig-003">Asset prices in the United States over historical periods</toc-entry>
        <toc-entry label="4." pagenum="21" xlink:href="fig-004">United States: out-of-sample forecast over the crisis period</toc-entry>
        <toc-entry label="5." pagenum="24" xlink:href="fig-005">Residuals of the long-term benchmark regression for Japan</toc-entry>
        <toc-entry label="6." pagenum="24" xlink:href="fig-006">Stocks of Japanese households wealth</toc-entry>
        <toc-entry label="7." pagenum="27" xlink:href="fig-007">Japan: out-of-sample forecast over the crisis period</toc-entry>
        <toc-entry label="8." pagenum="30" xlink:href="fig-008">Residuals of the long-term benchmark regression for the euro area</toc-entry>
        <toc-entry label="9." pagenum="30" xlink:href="fig-009">Stocks of euro area households wealth</toc-entry>
        <toc-entry label="10." pagenum="31" xlink:href="fig-010">Euro area: out-of-sample forecast over the crisis period</toc-entry>
        <toc-entry label="11." pagenum="34" xlink:href="fig-011">Percentage increase in consumption following a 1% step increase in net financial wealth</toc-entry>
        <toc-entry label="12." pagenum="34" xlink:href="fig-012">Dollar increase in consumption following a $100 step increase in net financial wealth</toc-entry>
        <toc-entry label="13." pagenum="34" xlink:href="fig-013">Percentage increase in consumption following a 1% increase in housing wealth</toc-entry>
        <toc-entry label="14." pagenum="34" xlink:href="fig-014">Dollar increase in consumption following a $100 step increase in housing wealth</toc-entry>
        <toc-entry label="15." pagenum="35" xlink:href="fig-015">Percentage increase in consumption following a 1% step increase in total wealth</toc-entry>
        <toc-entry label="16." pagenum="35" xlink:href="fig-016">Dollar increase in consumption following a $100 step increase in total wealth</toc-entry>
        <toc-entry label="17." pagenum="36" xlink:href="fig-017">Compared forecasting errors on the (annualised) growth rate of US consumption</toc-entry>
        <toc-entry label="18." pagenum="36" xlink:href="fig-018">Compared forecasting errors on the (annualised) growth rate of consumption in Japan</toc-entry>
        <toc-entry label="19." pagenum="37" xlink:href="fig-019">Compared forecasting errors on the (annualised) growth rate of euro area consumption</toc-entry>
        <toc-entry label="20." pagenum="38" xlink:href="fig-020">US household saving rate and its sensitivity to asset prices</toc-entry>
        <toc-entry label="21." pagenum="39" xlink:href="fig-021">US household saving rate and its sensitivity to credit conditions</toc-entry>
        <toc-entry label="22." pagenum="39" xlink:href="fig-022">The US credit supply index and alternative projections used in the scenarios</toc-entry>


    </toc-sect>

    <!-- FAKE SECTION ADDED FOR LINKING VALIDATION -->
    <!-- CAN BE IGNORED - NOT TO BE MODELLED -->

    <toc-sect>
        <title/>
        <toc-entry xml:id="abs-0001"/>
        <toc-entry xml:id="art-0001"/>
    </toc-sect>


</toc>
